server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/walden_big_event
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case=: true

