server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/walden_big_event
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
mybatis:
  configuration:
    map-underscore-to-camel-case=: true
ocr:
  apikey: "kV3fG58lnJKsfM3IrrogKiOw"
  secretkey: "7BmavrJniHLZOgk3v7pw1uUp57EjNI97"

